language: erlang
otp_release:
    - 17.0
    - 17.1
env:
    - ELIXIR=v0.15.2
before_install:
    - wget -q https://github.com/elixir-lang/elixir/releases/download/$ELIXIR/Precompiled.zip
    - unzip -qq -d elixir Precompiled.zip
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
    - mix local.hex --force
script:
    - mix make
    - mix test
    - mix bench
