language: erlang
otp_release:
    - 17.0
    - 17.1
before_install:
    - git clone git://github.com/elixir-lang/elixir.git
    - cd elixir
    - git checkout v0.15.1
    - make
    - cd ..
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
    - mix local.hex --force
    - mix deps.get --only test
script:
    - mix test
